# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 22:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160912_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 12, 7, 16, 31, 282382), verbose_name='date published'),
        ),
    ]
