# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 14:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20161011_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 12, 23, 29, 52, 291211), verbose_name='date published'),
        ),
    ]
