# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 14:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20161012_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='post',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 14, 23, 23, 18, 879930), verbose_name='date published'),
        ),
    ]
