# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 01:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20161014_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='product',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorites',
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 16, 10, 29, 54, 582095), verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
